apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: tictactoe
type: Opaque
data:
  username: #{REDIS_USERNAME} # Octopus deploy will replace this with real values and run the command
  password: #{REDIS_PASSWORD}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: tictactoe
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: redis
  namespace: tictactoe
spec:
  selector:
    matchLabels:
      app: redis  
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis  
    spec:
      containers:
        - name: redis
          image: redis:3.2-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "$(REDIS_PASS)"]
          ports:
            - containerPort: 6379
              name: redis
          env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: REDIS_PASS