kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  namespace: tictactoe
  labels:
    type: local
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tictactoe
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
   - port: 3306
  selector:
   app: mysql
---
apiVersion: extensions/v1
kind: Deployment
metadata:
  name: mysql
  namespace: tictactoe
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-pv-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv-volume
          persistentVolumeClaim:
            claimName: mysql-volumeclaim
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mysql
  namespace: tictactoe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mysql
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status:
  observedGeneration: 1
  lastScaleTime: <some-time>
  currentReplicas: 1
  desiredReplicas: 2
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
